# Generated by Django 6.0.1 on 2026-01-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('ciudad', models.CharField(default='Cali', max_length=50)),
                ('biografia', models.TextField(verbose_name='Descripción o Biografía')),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('whatsapp', models.CharField(help_text='Ej: 573001234567', max_length=20)),
                ('foto_principal', models.ImageField(upload_to='fotos_perfiles/')),
                ('verificada', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
