# Generated by Django 6.0.1 on 2026-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoria',
            field=models.CharField(choices=[('BASIC', 'Estándar'), ('GOLD', 'Gold'), ('PLATINUM', 'Platino')], default='BASIC', max_length=10),
        ),
    ]
