# Generated by Django 6.0.1 on 2026-01-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_perfil_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_central', models.CharField(help_text='Número central de la agencia (Ej: 573001234567)', max_length=20)),
                ('email_reservas', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Configuración Agencia',
                'verbose_name_plural': 'Configuración Agencia',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BASIC', 'Estándar'), ('GOLD', 'Gold'), ('PLATINUM', 'Platino')], max_length=10, unique=True)),
                ('precio_hora', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio x Hora')),
                ('precio_servicio_completo', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('incluye_jacuzzi', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='precio_hora',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia_larga',
            field=models.TextField(default='Información detallada pendiente.', verbose_name='Biografía Detallada'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='descripcion_corta',
            field=models.CharField(default='Modelo Exclusiva', help_text='Frase gancho para el card', max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='en_tiempo_real',
            field=models.BooleanField(default=False, verbose_name='En Tiempo Real'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_perfiles/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='profiles.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='profiles.tarifa'),
        ),
    ]
