# Generated by Django 6.0.1 on 2026-01-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_configuracionagencia_tarifa_remove_perfil_biografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='precio_30_min',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio x 30 Min'),
        ),
    ]
