# Generated by Django 6.0.1 on 2026-01-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_tarifa_precio_30_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='en_tiempo_real',
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('DESCANSO', 'En Descanso'), ('NO_DISPONIBLE', 'No Disponible')], default='NO_DISPONIBLE', max_length=20, verbose_name='Estado Actual'),
        ),
    ]
