# Generated by Django 6.0.1 on 2026-01-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_perfil_en_tiempo_real_perfil_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='nombre',
            field=models.CharField(choices=[('BASIC', 'Estándar'), ('GOLD', 'Gold'), ('PLATINUM', 'Platino')], max_length=10),
        ),
    ]
